name: Build Projects
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build DBUnit
        run: cd 3-integration-tests/dbunit && mvn verify -DskipTests
      - name: Build Jersey
        run: cd 3-integration-tests/jersey && mvn verify -DskipTests
      - name: Build WarpUnit
        run: cd 3-integration-tests/ && echo "TBD"
      - name: Build password-example
        run: cd 2-entry-to-tdd/password-example && mvn verify -DskipTests
