name: Build Projects
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # skip tests because they should fail or do not exist
      - name: Build tdd-example
        run: cd 2-entry-to-tdd && mvn verify -DskipTests
      - name: Build integration-tests-example
        run: cd 3-integration-tests && mvn verify -DskipTests
      - name: Build mocking-example
        run: cd 4-mocking && mvn verify -DskipTests
